# Form implementation generated from reading ui file 'register_window.ui'
#
# Created by: PyQt6 UI code generator 6.7.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(760, 474)
        Dialog.setStyleSheet("background-color: rgb(45, 44, 44);\n"
                             "                color: white;\n"
                             "            ")
        self.layoutWidget = QtWidgets.QWidget(parent=Dialog)
        self.layoutWidget.setGeometry(QtCore.QRect(20, 10, 731, 391))
        self.layoutWidget.setObjectName("layoutWidget")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.label_58 = QtWidgets.QLabel(parent=self.layoutWidget)
        self.label_58.setMinimumSize(QtCore.QSize(40, 40))
        self.label_58.setMaximumSize(QtCore.QSize(270, 270))
        self.label_58.setText("")
        self.label_58.setPixmap(QtGui.QPixmap(
            ":/res/kisspng-user-profile-2018-in-sight-user-conference-expo-5b554c0968c377.0307553315323166814291-fotor-bg-remover-20241102121640.png"))
        self.label_58.setScaledContents(True)
        self.label_58.setObjectName("label_58")
        self.verticalLayout_4.addWidget(self.label_58)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum,
                                           QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout_4.addItem(spacerItem)
        self.horizontalLayout_31 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_31.setObjectName("horizontalLayout_31")
        self.label_75 = QtWidgets.QLabel(parent=self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label_75.setFont(font)
        self.label_75.setObjectName("label_75")
        self.horizontalLayout_31.addWidget(self.label_75)
        self.lineEdit_level_reg_3 = QtWidgets.QLineEdit(parent=self.layoutWidget)
        self.lineEdit_level_reg_3.setMaximumSize(QtCore.QSize(250, 16777215))
        self.lineEdit_level_reg_3.setSizeIncrement(QtCore.QSize(0, 0))
        self.lineEdit_level_reg_3.setStyleSheet("QLineEdit {\n"
                                                "                                        border: 2px solid white;\n"
                                                "                                        border-radius: 10px;\n"
                                                "                                        color: white;\n"
                                                "\n"
                                                "                                        }\n"
                                                "                                    ")
        self.lineEdit_level_reg_3.setObjectName("lineEdit_level_reg_3")
        self.horizontalLayout_31.addWidget(self.lineEdit_level_reg_3)
        self.verticalLayout_4.addLayout(self.horizontalLayout_31)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.label_76 = QtWidgets.QLabel(parent=self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label_76.setFont(font)
        self.label_76.setObjectName("label_76")
        self.horizontalLayout_6.addWidget(self.label_76)
        self.lineEdit_age_reg_3 = QtWidgets.QLineEdit(parent=self.layoutWidget)
        self.lineEdit_age_reg_3.setMaximumSize(QtCore.QSize(250, 16777215))
        self.lineEdit_age_reg_3.setSizeIncrement(QtCore.QSize(0, 0))
        self.lineEdit_age_reg_3.setStyleSheet("QLineEdit {\n"
                                              "                                        border: 2px solid white;\n"
                                              "                                        border-radius: 10px;\n"
                                              "                                        color: white;\n"
                                              "\n"
                                              "                                        }\n"
                                              "                                    ")
        self.lineEdit_age_reg_3.setObjectName("lineEdit_age_reg_3")
        self.horizontalLayout_6.addWidget(self.lineEdit_age_reg_3)
        self.verticalLayout_4.addLayout(self.horizontalLayout_6)
        self.horizontalLayout_44 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_44.setObjectName("horizontalLayout_44")
        self.label_77 = QtWidgets.QLabel(parent=self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label_77.setFont(font)
        self.label_77.setObjectName("label_77")
        self.horizontalLayout_44.addWidget(self.label_77)
        self.lineEdit_expirience_reg_3 = QtWidgets.QLineEdit(parent=self.layoutWidget)
        self.lineEdit_expirience_reg_3.setMaximumSize(QtCore.QSize(250, 16777215))
        self.lineEdit_expirience_reg_3.setSizeIncrement(QtCore.QSize(0, 0))
        self.lineEdit_expirience_reg_3.setStyleSheet("QLineEdit {\n"
                                                     "                                        border: 2px solid white;\n"
                                                     "                                        border-radius: 10px;\n"
                                                     "                                        color: white;\n"
                                                     "\n"
                                                     "                                        }\n"
                                                     "                                    ")
        self.lineEdit_expirience_reg_3.setObjectName("lineEdit_expirience_reg_3")
        self.horizontalLayout_44.addWidget(self.lineEdit_expirience_reg_3)
        self.verticalLayout_4.addLayout(self.horizontalLayout_44)
        self.horizontalLayout_5.addLayout(self.verticalLayout_4)
        self.verticalLayout_13 = QtWidgets.QVBoxLayout()
        self.verticalLayout_13.setObjectName("verticalLayout_13")
        self.horizontalLayout_45 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_45.setObjectName("horizontalLayout_45")
        self.label_78 = QtWidgets.QLabel(parent=self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label_78.setFont(font)
        self.label_78.setObjectName("label_78")
        self.horizontalLayout_45.addWidget(self.label_78)
        self.lineEdit_login_reg_3 = QtWidgets.QLineEdit(parent=self.layoutWidget)
        self.lineEdit_login_reg_3.setMaximumSize(QtCore.QSize(250, 16777215))
        self.lineEdit_login_reg_3.setSizeIncrement(QtCore.QSize(0, 0))
        self.lineEdit_login_reg_3.setStyleSheet("QLineEdit {\n"
                                                "                                                border: 2px solid white;\n"
                                                "                                                border-radius: 10px;\n"
                                                "                                                color: white;\n"
                                                "\n"
                                                "                                                }\n"
                                                "                                            ")
        self.lineEdit_login_reg_3.setObjectName("lineEdit_login_reg_3")
        self.horizontalLayout_45.addWidget(self.lineEdit_login_reg_3)
        self.verticalLayout_13.addLayout(self.horizontalLayout_45)
        self.horizontalLayout_46 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_46.setObjectName("horizontalLayout_46")
        self.label_79 = QtWidgets.QLabel(parent=self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label_79.setFont(font)
        self.label_79.setObjectName("label_79")
        self.horizontalLayout_46.addWidget(self.label_79)
        self.lineEdit_paswword_reg_3 = QtWidgets.QLineEdit(parent=self.layoutWidget)
        self.lineEdit_paswword_reg_3.setMaximumSize(QtCore.QSize(250, 16777215))
        self.lineEdit_paswword_reg_3.setSizeIncrement(QtCore.QSize(0, 0))
        self.lineEdit_paswword_reg_3.setStyleSheet("QLineEdit {\n"
                                                   "                                                border: 2px solid white;\n"
                                                   "                                                border-radius: 10px;\n"
                                                   "                                                color: white;\n"
                                                   "\n"
                                                   "                                                }\n"
                                                   "                                            ")
        self.lineEdit_paswword_reg_3.setObjectName("lineEdit_paswword_reg_3")
        self.horizontalLayout_46.addWidget(self.lineEdit_paswword_reg_3)
        self.verticalLayout_13.addLayout(self.horizontalLayout_46)
        self.horizontalLayout_47 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_47.setObjectName("horizontalLayout_47")
        self.label_80 = QtWidgets.QLabel(parent=self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label_80.setFont(font)
        self.label_80.setObjectName("label_80")
        self.horizontalLayout_47.addWidget(self.label_80)
        self.lineEdit_midlname_reg_3 = QtWidgets.QLineEdit(parent=self.layoutWidget)
        self.lineEdit_midlname_reg_3.setMaximumSize(QtCore.QSize(250, 16777215))
        self.lineEdit_midlname_reg_3.setSizeIncrement(QtCore.QSize(0, 0))
        self.lineEdit_midlname_reg_3.setStyleSheet("QLineEdit {\n"
                                                   "                                                border: 2px solid white;\n"
                                                   "                                                border-radius: 10px;\n"
                                                   "                                                color: white;\n"
                                                   "\n"
                                                   "                                                }\n"
                                                   "                                            ")
        self.lineEdit_midlname_reg_3.setObjectName("lineEdit_midlname_reg_3")
        self.horizontalLayout_47.addWidget(self.lineEdit_midlname_reg_3)
        self.verticalLayout_13.addLayout(self.horizontalLayout_47)
        self.horizontalLayout_48 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_48.setObjectName("horizontalLayout_48")
        self.label_81 = QtWidgets.QLabel(parent=self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label_81.setFont(font)
        self.label_81.setObjectName("label_81")
        self.horizontalLayout_48.addWidget(self.label_81)
        self.lineEdit_secondname_reg_3 = QtWidgets.QLineEdit(parent=self.layoutWidget)
        self.lineEdit_secondname_reg_3.setMaximumSize(QtCore.QSize(250, 16777215))
        self.lineEdit_secondname_reg_3.setSizeIncrement(QtCore.QSize(0, 0))
        self.lineEdit_secondname_reg_3.setStyleSheet("QLineEdit {\n"
                                                     "                                                border: 2px solid white;\n"
                                                     "                                                border-radius: 10px;\n"
                                                     "                                                color: white;\n"
                                                     "\n"
                                                     "                                                }\n"
                                                     "                                            ")
        self.lineEdit_secondname_reg_3.setObjectName("lineEdit_secondname_reg_3")
        self.horizontalLayout_48.addWidget(self.lineEdit_secondname_reg_3)
        self.verticalLayout_13.addLayout(self.horizontalLayout_48)
        self.horizontalLayout_49 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_49.setObjectName("horizontalLayout_49")
        self.label_82 = QtWidgets.QLabel(parent=self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label_82.setFont(font)
        self.label_82.setObjectName("label_82")
        self.horizontalLayout_49.addWidget(self.label_82)
        self.lineEdit_name_reg_3 = QtWidgets.QLineEdit(parent=self.layoutWidget)
        self.lineEdit_name_reg_3.setMaximumSize(QtCore.QSize(250, 16777215))
        self.lineEdit_name_reg_3.setSizeIncrement(QtCore.QSize(0, 0))
        self.lineEdit_name_reg_3.setStyleSheet("QLineEdit {\n"
                                               "                                                border: 2px solid white;\n"
                                               "                                                border-radius: 10px;\n"
                                               "                                                color: white;\n"
                                               "\n"
                                               "                                                }\n"
                                               "                                            ")
        self.lineEdit_name_reg_3.setObjectName("lineEdit_name_reg_3")
        self.horizontalLayout_49.addWidget(self.lineEdit_name_reg_3)
        self.verticalLayout_13.addLayout(self.horizontalLayout_49)
        self.horizontalLayout_50 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_50.setObjectName("horizontalLayout_50")
        self.label_83 = QtWidgets.QLabel(parent=self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label_83.setFont(font)
        self.label_83.setObjectName("label_83")
        self.horizontalLayout_50.addWidget(self.label_83)
        self.lineEdit_post_reg_3 = QtWidgets.QLineEdit(parent=self.layoutWidget)
        self.lineEdit_post_reg_3.setMaximumSize(QtCore.QSize(250, 16777215))
        self.lineEdit_post_reg_3.setSizeIncrement(QtCore.QSize(0, 0))
        self.lineEdit_post_reg_3.setStyleSheet("QLineEdit {\n"
                                               "                                                border: 2px solid white;\n"
                                               "                                                border-radius: 10px;\n"
                                               "                                                color: white;\n"
                                               "\n"
                                               "                                                }\n"
                                               "                                            ")
        self.lineEdit_post_reg_3.setObjectName("lineEdit_post_reg_3")
        self.horizontalLayout_50.addWidget(self.lineEdit_post_reg_3)
        self.verticalLayout_13.addLayout(self.horizontalLayout_50)
        self.horizontalLayout_5.addLayout(self.verticalLayout_13)
        self.pushButton_reg_reg_2 = QtWidgets.QPushButton(parent=Dialog)
        self.pushButton_reg_reg_2.setGeometry(QtCore.QRect(30, 420, 721, 41))
        self.pushButton_reg_reg_2.setStyleSheet("background-color: rgb(0, 153, 81);\n"
                                                "                            color: white;\n"
                                                "                            border-radius: 20px;\n"
                                                "                        ")
        self.pushButton_reg_reg_2.setObjectName("pushButton_reg_reg_2")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label_75.setText(_translate("Dialog", "Разряд"))
        self.label_76.setText(_translate("Dialog", "Возраст"))
        self.label_77.setText(_translate("Dialog", "Стаж"))
        self.label_78.setText(_translate("Dialog", "Никнейм"))
        self.label_79.setText(_translate("Dialog", "Пароль"))
        self.label_80.setText(_translate("Dialog", "Отчество"))
        self.label_81.setText(_translate("Dialog", "Фамилия"))
        self.label_82.setText(_translate("Dialog", "Имя"))
        self.label_83.setText(_translate("Dialog", "Должность"))
        self.pushButton_reg_reg_2.setText(_translate("Dialog", "Регистрация"))
