# Form implementation generated from reading ui file 'menu_user.ui'
#
# Created by: PyQt6 UI code generator 6.7.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets
import os


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1152, 815)
        font = QtGui.QFont()
        font.setPointSize(16)
        MainWindow.setFont(font)
        MainWindow.setStyleSheet("background-color: rgb(45, 44, 44);\n"
                                 "                color: white\n"
                                 "            ")
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setHorizontalSpacing(0)
        self.gridLayout.setVerticalSpacing(6)
        self.gridLayout.setObjectName("gridLayout")
        self.widget_4 = QtWidgets.QWidget(parent=self.centralwidget)
        self.widget_4.setStyleSheet("QWidget{\n"
                                    "                                background-color: rgb(0, 85, 0);\n"
                                    "                                border-top-right-radius:20px;\n"
                                    "                                }\n"
                                    "                                QPushButton{\n"
                                    "                                color: white;\n"
                                    "\n"
                                    "                                height: 30px;\n"
                                    "                                border:none;\n"
                                    "                                border-radius: 10px;\n"
                                    "                                border-bottom-radius: 10px;\n"
                                    "\n"
                                    "                                }\n"
                                    "                                QPushButton:checked{\n"
                                    "                                color: rgb(0, 85, 0);\n"
                                    "                                background-color: white;\n"
                                    "\n"
                                    "                                }\n"
                                    "                            ")
        self.widget_4.setObjectName("widget_4")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.widget_4)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_3 = QtWidgets.QLabel(parent=self.widget_4)
        self.label_3.setMaximumSize(QtCore.QSize(55, 55))
        self.label_3.setText("")
        self.label_3.setPixmap(QtGui.QPixmap(os.path.abspath(
            "/res/kisspng-user-profile-2018-in-sight-user-conference-expo-5b554c0968c377.0307553315323166814291-fotor-bg-remover-20241102121640.png")))
        self.label_3.setScaledContents(True)
        self.label_3.setObjectName("label_3")
        self.verticalLayout.addWidget(self.label_3)
        self.label_nick = QtWidgets.QLabel(parent=self.widget_4)
        self.label_nick.setObjectName("label_nick")
        self.verticalLayout.addWidget(self.label_nick)
        self.verticalLayout_4.addLayout(self.verticalLayout)
        self.verticalLayout_7 = QtWidgets.QVBoxLayout()
        self.verticalLayout_7.setSpacing(15)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.pushButton_acc1_us = QtWidgets.QPushButton(parent=self.widget_4)
        self.pushButton_acc1_us.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(os.path.abspath("/res/add_24dp_FFFFFF_FILL0_wght400_GRAD0_opsz24.png")),
                       QtGui.QIcon.Mode.Normal,
                       QtGui.QIcon.State.Off)
        icon.addPixmap(QtGui.QPixmap(os.path.abspath("/res/add_24dp_005500_FILL0_wght400_GRAD0_opsz24.png")),
                       QtGui.QIcon.Mode.Normal,
                       QtGui.QIcon.State.On)
        self.pushButton_acc1_us.setIcon(icon)
        self.pushButton_acc1_us.setCheckable(True)
        self.pushButton_acc1_us.setAutoExclusive(True)
        self.pushButton_acc1_us.setObjectName("pushButton_acc1_us")
        self.verticalLayout_7.addWidget(self.pushButton_acc1_us)
        self.pushButton_education1us = QtWidgets.QPushButton(parent=self.widget_4)
        self.pushButton_education1us.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(os.path.abspath("/res/school_24dp_FFFFFF_FILL0_wght400_GRAD0_opsz24.png")),
                        QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        icon1.addPixmap(QtGui.QPixmap(os.path.abspath("/res/school_24dp_005500_FILL0_wght400_GRAD0_opsz24.png")),
                        QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.On)
        self.pushButton_education1us.setIcon(icon1)
        self.pushButton_education1us.setCheckable(True)
        self.pushButton_education1us.setAutoExclusive(True)
        self.pushButton_education1us.setObjectName("pushButton_education1us")
        self.verticalLayout_7.addWidget(self.pushButton_education1us)
        self.pushButton_orde1_2 = QtWidgets.QPushButton(parent=self.widget_4)
        self.pushButton_orde1_2.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(os.path.abspath("/res/summarize_24dp_FFFFFF_FILL0_wght400_GRAD0_opsz24.png")),
                        QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        icon2.addPixmap(QtGui.QPixmap(os.path.abspath("/res/summarize_24dp_005500_FILL0_wght400_GRAD0_opsz24.png")),
                        QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.On)
        self.pushButton_orde1_2.setIcon(icon2)
        self.pushButton_orde1_2.setCheckable(True)
        self.pushButton_orde1_2.setAutoExclusive(True)
        self.pushButton_orde1_2.setObjectName("pushButton_orde1_2")
        self.verticalLayout_7.addWidget(self.pushButton_orde1_2)
        self.pushButton_task1 = QtWidgets.QPushButton(parent=self.widget_4)
        self.pushButton_task1.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(os.path.abspath("/res/work_24dp_FFFFFF_FILL0_wght400_GRAD0_opsz24.png")),
                        QtGui.QIcon.Mode.Normal,
                        QtGui.QIcon.State.Off)
        icon3.addPixmap(QtGui.QPixmap(os.path.abspath("/res/work_24dp_005500_FILL0_wght400_GRAD0_opsz24.png")),
                        QtGui.QIcon.Mode.Normal,
                        QtGui.QIcon.State.On)
        self.pushButton_task1.setIcon(icon3)
        self.pushButton_task1.setCheckable(True)
        self.pushButton_task1.setAutoExclusive(True)
        self.pushButton_task1.setObjectName("pushButton_task1")
        self.verticalLayout_7.addWidget(self.pushButton_task1)
        self.verticalLayout_4.addLayout(self.verticalLayout_7)
        spacerItem = QtWidgets.QSpacerItem(20, 278, QtWidgets.QSizePolicy.Policy.Minimum,
                                           QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout_4.addItem(spacerItem)
        self.pushButton_logout1 = QtWidgets.QPushButton(parent=self.widget_4)
        self.pushButton_logout1.setText("")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(os.path.abspath("/res/logout_24dp_FFFFFF_FILL0_wght400_GRAD0_opsz24.png")),
                        QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        icon4.addPixmap(QtGui.QPixmap(os.path.abspath("/res/logout_24dp_005500_FILL0_wght400_GRAD0_opsz24.png")),
                        QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.On)
        self.pushButton_logout1.setIcon(icon4)
        self.pushButton_logout1.setCheckable(True)
        self.pushButton_logout1.setAutoExclusive(True)
        self.pushButton_logout1.setObjectName("pushButton_logout1")
        self.verticalLayout_4.addWidget(self.pushButton_logout1)
        self.gridLayout.addWidget(self.widget_4, 1, 0, 1, 1)
        self.widget_2 = QtWidgets.QWidget(parent=self.centralwidget)
        self.widget_2.setObjectName("widget_2")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.widget_2)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout()
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.pushButton = QtWidgets.QPushButton(parent=self.widget_2)
        self.pushButton.setMaximumSize(QtCore.QSize(40, 40))
        self.pushButton.setStyleSheet("border:none;\n"
                                      "                                                ")
        self.pushButton.setText("")
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(os.path.abspath("/res/menu_24dp_FFFFFF_FILL0_wght400_GRAD0_opsz24.png")),
                        QtGui.QIcon.Mode.Normal,
                        QtGui.QIcon.State.Off)
        self.pushButton.setIcon(icon5)
        self.pushButton.setIconSize(QtCore.QSize(50, 50))
        self.pushButton.setCheckable(True)
        self.pushButton.setAutoExclusive(True)
        self.pushButton.setObjectName("pushButton")
        self.verticalLayout_8.addWidget(self.pushButton)
        self.horizontalLayout_4.addLayout(self.verticalLayout_8)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding,
                                            QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem1)
        self.label = QtWidgets.QLabel(parent=self.widget_2)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.horizontalLayout_4.addWidget(self.label)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding,
                                            QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem2)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.pushButton_13 = QtWidgets.QPushButton(parent=self.widget_2)
        self.pushButton_13.setText("")
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(os.path.abspath("/res/remove_24dp_FFFFFF_FILL0_wght400_GRAD0_opsz24.png")),
                        QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.pushButton_13.setIcon(icon6)
        self.pushButton_13.setCheckable(True)
        self.pushButton_13.setObjectName("pushButton_13")
        self.horizontalLayout.addWidget(self.pushButton_13)
        self.pushButton_24 = QtWidgets.QPushButton(parent=self.widget_2)
        self.pushButton_24.setText("")
        icon7 = QtGui.QIcon()
        icon7.addPixmap(
            QtGui.QPixmap(os.path.abspath("/res/check_box_outline_blank_24dp_FFFFFF_FILL0_wght400_GRAD0_opsz24.png")),
            QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.pushButton_24.setIcon(icon7)
        self.pushButton_24.setCheckable(True)
        self.pushButton_24.setObjectName("pushButton_24")
        self.horizontalLayout.addWidget(self.pushButton_24)
        self.pushButton_22 = QtWidgets.QPushButton(parent=self.widget_2)
        self.pushButton_22.setText("")
        self.pushButton_22.setIcon(icon7)
        self.pushButton_22.setCheckable(True)
        self.pushButton_22.setObjectName("pushButton_22")
        self.horizontalLayout.addWidget(self.pushButton_22)
        self.pushButton_23 = QtWidgets.QPushButton(parent=self.widget_2)
        self.pushButton_23.setText("")
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap(os.path.abspath("/res/close_24dp_FFFFFF_FILL0_wght400_GRAD0_opsz24.png")),
                        QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.pushButton_23.setIcon(icon8)
        self.pushButton_23.setCheckable(True)
        self.pushButton_23.setAutoExclusive(True)
        self.pushButton_23.setObjectName("pushButton_23")
        self.horizontalLayout.addWidget(self.pushButton_23)
        self.horizontalLayout_4.addLayout(self.horizontalLayout)
        self.gridLayout.addWidget(self.widget_2, 0, 0, 1, 4)
        self.widget_5 = QtWidgets.QWidget(parent=self.centralwidget)
        self.widget_5.setStyleSheet("QWidget{\n"
                                    "                                background-color: rgb(0, 85, 0);\n"
                                    "                                border-top-right-radius:20px;\n"
                                    "                                }\n"
                                    "\n"
                                    "                                QPushButton{\n"
                                    "                                color: white;\n"
                                    "                                text-align:left;\n"
                                    "                                height: 30px;\n"
                                    "                                border:none;\n"
                                    "                                border-radius: 10px;\n"
                                    "                                border-bottom-radius: 10px;\n"
                                    "\n"
                                    "                                }\n"
                                    "                                QPushButton:checked{\n"
                                    "                                color: rgb(0, 85, 0);\n"
                                    "                                background-color: white;\n"
                                    "\n"
                                    "                                }\n"
                                    "                            ")
        self.widget_5.setObjectName("widget_5")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.widget_5)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label_5 = QtWidgets.QLabel(parent=self.widget_5)
        self.label_5.setMaximumSize(QtCore.QSize(55, 55))
        self.label_5.setText("")
        self.label_5.setPixmap(QtGui.QPixmap(os.path.abspath(
            "/res/kisspng-user-profile-2018-in-sight-user-conference-expo-5b554c0968c377.0307553315323166814291-fotor-bg-remover-20241102121640.png")))
        self.label_5.setScaledContents(True)
        self.label_5.setObjectName("label_5")
        self.verticalLayout_3.addWidget(self.label_5)
        self.label_nick2 = QtWidgets.QLabel(parent=self.widget_5)
        self.label_nick2.setObjectName("label_nick2")
        self.verticalLayout_3.addWidget(self.label_nick2)
        self.verticalLayout_5.addLayout(self.verticalLayout_3)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setSpacing(15)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.pushButton_acc2_us = QtWidgets.QPushButton(parent=self.widget_5)
        self.pushButton_acc2_us.setIcon(icon)
        self.pushButton_acc2_us.setCheckable(True)
        self.pushButton_acc2_us.setAutoExclusive(True)
        self.pushButton_acc2_us.setObjectName("pushButton_acc2_us")
        self.verticalLayout_2.addWidget(self.pushButton_acc2_us)
        self.pushButton_education2_us = QtWidgets.QPushButton(parent=self.widget_5)
        self.pushButton_education2_us.setIcon(icon1)
        self.pushButton_education2_us.setCheckable(True)
        self.pushButton_education2_us.setAutoExclusive(True)
        self.pushButton_education2_us.setObjectName("pushButton_education2_us")
        self.verticalLayout_2.addWidget(self.pushButton_education2_us)
        self.pushButton_order2_2 = QtWidgets.QPushButton(parent=self.widget_5)
        self.pushButton_order2_2.setIcon(icon2)
        self.pushButton_order2_2.setCheckable(True)
        self.pushButton_order2_2.setAutoExclusive(True)
        self.pushButton_order2_2.setObjectName("pushButton_order2_2")
        self.verticalLayout_2.addWidget(self.pushButton_order2_2)
        self.pushButton_tasks2 = QtWidgets.QPushButton(parent=self.widget_5)
        self.pushButton_tasks2.setIcon(icon3)
        self.pushButton_tasks2.setCheckable(True)
        self.pushButton_tasks2.setAutoExclusive(True)
        self.pushButton_tasks2.setObjectName("pushButton_tasks2")
        self.verticalLayout_2.addWidget(self.pushButton_tasks2)
        self.verticalLayout_5.addLayout(self.verticalLayout_2)
        spacerItem3 = QtWidgets.QSpacerItem(20, 273, QtWidgets.QSizePolicy.Policy.Minimum,
                                            QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout_5.addItem(spacerItem3)
        self.pushButton_12 = QtWidgets.QPushButton(parent=self.widget_5)
        self.pushButton_12.setStyleSheet("")
        self.pushButton_12.setIcon(icon4)
        self.pushButton_12.setCheckable(True)
        self.pushButton_12.setAutoExclusive(True)
        self.pushButton_12.setObjectName("pushButton_12")
        self.verticalLayout_5.addWidget(self.pushButton_12)
        self.gridLayout.addWidget(self.widget_5, 1, 1, 1, 1)
        self.widget_3 = QtWidgets.QWidget(parent=self.centralwidget)
        self.widget_3.setObjectName("widget_3")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.widget_3)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.stackedWidget = QtWidgets.QStackedWidget(parent=self.widget_3)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.stackedWidget.setFont(font)
        self.stackedWidget.setStyleSheet("background-color: rgb(45, 44, 44);")
        self.stackedWidget.setObjectName("stackedWidget")
        self.education_page = QtWidgets.QWidget()
        self.education_page.setObjectName("education_page")
        self.label_12 = QtWidgets.QLabel(parent=self.education_page)
        self.label_12.setGeometry(QtCore.QRect(10, 50, 261, 291))
        self.label_12.setMinimumSize(QtCore.QSize(261, 291))
        self.label_12.setMaximumSize(QtCore.QSize(261, 291))
        self.label_12.setStyleSheet("border-radius:20px;\n"
                                    "                                                ")
        self.label_12.setText("")
        self.label_12.setPixmap(QtGui.QPixmap(os.path.abspath("/res/dude.png")))
        self.label_12.setScaledContents(True)
        self.label_12.setObjectName("label_12")
        self.label_17 = QtWidgets.QLabel(parent=self.education_page)
        self.label_17.setGeometry(QtCore.QRect(290, 50, 281, 291))
        self.label_17.setText("")
        self.label_17.setPixmap(QtGui.QPixmap(os.path.abspath("/res/dude2.png")))
        self.label_17.setScaledContents(True)
        self.label_17.setObjectName("label_17")
        self.label_25 = QtWidgets.QLabel(parent=self.education_page)
        self.label_25.setGeometry(QtCore.QRect(590, 50, 271, 291))
        self.label_25.setText("")
        self.label_25.setPixmap(QtGui.QPixmap(os.path.abspath("/res/dude1.png")))
        self.label_25.setScaledContents(True)
        self.label_25.setObjectName("label_25")
        self.pushButton_link1 = QtWidgets.QPushButton(parent=self.education_page)
        self.pushButton_link1.setGeometry(QtCore.QRect(20, 510, 261, 41))
        self.pushButton_link1.setStyleSheet("background-color: rgb(0, 153, 81);\n"
                                            "                                                    color: white;\n"
                                            "                                                    border-radius: 20px;\n"
                                            "                                                ")
        self.pushButton_link1.setObjectName("pushButton_link1")
        self.pushButton_link2 = QtWidgets.QPushButton(parent=self.education_page)
        self.pushButton_link2.setGeometry(QtCore.QRect(310, 510, 261, 41))
        self.pushButton_link2.setStyleSheet("background-color: rgb(0, 153, 81);\n"
                                            "                                                    color: white;\n"
                                            "                                                    border-radius: 20px;\n"
                                            "                                                ")
        self.pushButton_link2.setObjectName("pushButton_link2")
        self.pushButton_link3 = QtWidgets.QPushButton(parent=self.education_page)
        self.pushButton_link3.setGeometry(QtCore.QRect(590, 510, 261, 41))
        self.pushButton_link3.setStyleSheet("background-color: rgb(0, 153, 81);\n"
                                            "                                                    color: white;\n"
                                            "                                                    border-radius: 20px;\n"
                                            "                                                ")
        self.pushButton_link3.setObjectName("pushButton_link3")
        self.label_31 = QtWidgets.QLabel(parent=self.education_page)
        self.label_31.setGeometry(QtCore.QRect(10, 360, 271, 121))
        self.label_31.setStyleSheet("QLabel{\n"
                                    "                                                    setWordWrap(true);\n"
                                    "                                                    }\n"
                                    "                                                ")
        self.label_31.setWordWrap(True)
        self.label_31.setObjectName("label_31")
        self.label_32 = QtWidgets.QLabel(parent=self.education_page)
        self.label_32.setGeometry(QtCore.QRect(300, 360, 271, 121))
        self.label_32.setWordWrap(True)
        self.label_32.setObjectName("label_32")
        self.label_33 = QtWidgets.QLabel(parent=self.education_page)
        self.label_33.setGeometry(QtCore.QRect(594, 365, 251, 131))
        self.label_33.setWordWrap(True)
        self.label_33.setObjectName("label_33")
        self.layoutWidget = QtWidgets.QWidget(parent=self.education_page)
        self.layoutWidget.setGeometry(QtCore.QRect(10, 10, 841, 27))
        self.layoutWidget.setObjectName("layoutWidget")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_30 = QtWidgets.QLabel(parent=self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label_30.setFont(font)
        self.label_30.setObjectName("label_30")
        self.horizontalLayout_2.addWidget(self.label_30)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding,
                                            QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem4)
        self.stackedWidget.addWidget(self.education_page)
        self.acc_page = QtWidgets.QWidget()
        self.acc_page.setObjectName("acc_page")
        self.verticalLayout_15 = QtWidgets.QVBoxLayout(self.acc_page)
        self.verticalLayout_15.setObjectName("verticalLayout_15")
        self.horizontalLayout_25 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_25.setObjectName("horizontalLayout_25")
        self.label_8 = QtWidgets.QLabel(parent=self.acc_page)
        self.label_8.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_8.sizePolicy().hasHeightForWidth())
        self.label_8.setSizePolicy(sizePolicy)
        self.label_8.setMinimumSize(QtCore.QSize(270, 270))
        self.label_8.setMaximumSize(QtCore.QSize(270, 270))
        self.label_8.setText("")
        self.label_8.setPixmap(QtGui.QPixmap(os.path.abspath(
            "/res/kisspng-user-profile-2018-in-sight-user-conference-expo-5b554c0968c377.0307553315323166814291-fotor-bg-remover-20241102121640.png")))
        self.label_8.setScaledContents(True)
        self.label_8.setObjectName("label_8")
        self.horizontalLayout_25.addWidget(self.label_8)
        self.verticalLayout_9 = QtWidgets.QVBoxLayout()
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.horizontalLayout_13 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        self.label_18 = QtWidgets.QLabel(parent=self.acc_page)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label_18.setFont(font)
        self.label_18.setObjectName("label_18")
        self.horizontalLayout_13.addWidget(self.label_18)
        self.label_nik = QtWidgets.QLabel(parent=self.acc_page)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label_nik.setFont(font)
        self.label_nik.setObjectName("label_nik")
        self.horizontalLayout_13.addWidget(self.label_nik)
        self.verticalLayout_9.addLayout(self.horizontalLayout_13)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.label_11 = QtWidgets.QLabel(parent=self.acc_page)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label_11.setFont(font)
        self.label_11.setObjectName("label_11")
        self.horizontalLayout_7.addWidget(self.label_11)
        self.label_midlename = QtWidgets.QLabel(parent=self.acc_page)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label_midlename.setFont(font)
        self.label_midlename.setObjectName("label_midlename")
        self.horizontalLayout_7.addWidget(self.label_midlename)
        self.verticalLayout_9.addLayout(self.horizontalLayout_7)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_9 = QtWidgets.QLabel(parent=self.acc_page)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label_9.setFont(font)
        self.label_9.setObjectName("label_9")
        self.horizontalLayout_5.addWidget(self.label_9)
        self.label_secondnaame = QtWidgets.QLabel(parent=self.acc_page)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label_secondnaame.setFont(font)
        self.label_secondnaame.setObjectName("label_secondnaame")
        self.horizontalLayout_5.addWidget(self.label_secondnaame)
        self.verticalLayout_9.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.label_10 = QtWidgets.QLabel(parent=self.acc_page)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label_10.setFont(font)
        self.label_10.setObjectName("label_10")
        self.horizontalLayout_6.addWidget(self.label_10)
        self.label_name = QtWidgets.QLabel(parent=self.acc_page)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label_name.setFont(font)
        self.label_name.setObjectName("label_name")
        self.horizontalLayout_6.addWidget(self.label_name)
        self.verticalLayout_9.addLayout(self.horizontalLayout_6)
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.label_16 = QtWidgets.QLabel(parent=self.acc_page)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label_16.setFont(font)
        self.label_16.setObjectName("label_16")
        self.horizontalLayout_8.addWidget(self.label_16)
        self.label_post = QtWidgets.QLabel(parent=self.acc_page)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label_post.setFont(font)
        self.label_post.setObjectName("label_post")
        self.horizontalLayout_8.addWidget(self.label_post)
        self.verticalLayout_9.addLayout(self.horizontalLayout_8)
        self.horizontalLayout_25.addLayout(self.verticalLayout_9)
        spacerItem5 = QtWidgets.QSpacerItem(270, 270, QtWidgets.QSizePolicy.Policy.Expanding,
                                            QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_25.addItem(spacerItem5)
        self.verticalLayout_15.addLayout(self.horizontalLayout_25)
        self.horizontalLayout_24 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_24.setObjectName("horizontalLayout_24")
        self.horizontalLayout_15 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_15.setObjectName("horizontalLayout_15")
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.label_13 = QtWidgets.QLabel(parent=self.acc_page)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label_13.setFont(font)
        self.label_13.setObjectName("label_13")
        self.horizontalLayout_9.addWidget(self.label_13)
        self.label_age = QtWidgets.QLabel(parent=self.acc_page)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label_age.setFont(font)
        self.label_age.setObjectName("label_age")
        self.horizontalLayout_9.addWidget(self.label_age)
        self.horizontalLayout_15.addLayout(self.horizontalLayout_9)
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.label_14 = QtWidgets.QLabel(parent=self.acc_page)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label_14.setFont(font)
        self.label_14.setObjectName("label_14")
        self.horizontalLayout_11.addWidget(self.label_14)
        self.label_level = QtWidgets.QLabel(parent=self.acc_page)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label_level.setFont(font)
        self.label_level.setObjectName("label_level")
        self.horizontalLayout_11.addWidget(self.label_level)
        self.horizontalLayout_15.addLayout(self.horizontalLayout_11)
        self.horizontalLayout_24.addLayout(self.horizontalLayout_15)
        spacerItem6 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding,
                                            QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_24.addItem(spacerItem6)
        self.verticalLayout_15.addLayout(self.horizontalLayout_24)
        self.horizontalLayout_23 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_23.setObjectName("horizontalLayout_23")
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.label_15 = QtWidgets.QLabel(parent=self.acc_page)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label_15.setFont(font)
        self.label_15.setObjectName("label_15")
        self.horizontalLayout_12.addWidget(self.label_15)
        self.label_exp = QtWidgets.QLabel(parent=self.acc_page)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label_exp.setFont(font)
        self.label_exp.setObjectName("label_exp")
        self.horizontalLayout_12.addWidget(self.label_exp)
        self.horizontalLayout_23.addLayout(self.horizontalLayout_12)
        spacerItem7 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding,
                                            QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_23.addItem(spacerItem7)
        self.verticalLayout_15.addLayout(self.horizontalLayout_23)
        self.verticalLayout_14 = QtWidgets.QVBoxLayout()
        self.verticalLayout_14.setObjectName("verticalLayout_14")
        self.horizontalLayout_22 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_22.setObjectName("horizontalLayout_22")
        self.label_34 = QtWidgets.QLabel(parent=self.acc_page)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label_34.setFont(font)
        self.label_34.setObjectName("label_34")
        self.horizontalLayout_22.addWidget(self.label_34)
        spacerItem8 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding,
                                            QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_22.addItem(spacerItem8)
        self.verticalLayout_14.addLayout(self.horizontalLayout_22)
        self.textEdit_pfil = QtWidgets.QTextEdit(parent=self.acc_page)
        self.textEdit_pfil.setStyleSheet("border: 2px solid white;\n"
                                         "                                                    border-radius: 10px;\n"
                                         "                                                    color: white;\n"
                                         "                                                ")
        self.textEdit_pfil.setObjectName("textEdit_pfil")
        self.verticalLayout_14.addWidget(self.textEdit_pfil)
        self.verticalLayout_15.addLayout(self.verticalLayout_14)
        self.stackedWidget.addWidget(self.acc_page)
        self.order_page = QtWidgets.QWidget()
        self.order_page.setObjectName("order_page")
        self.verticalLayout_12 = QtWidgets.QVBoxLayout(self.order_page)
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        self.label_35 = QtWidgets.QLabel(parent=self.order_page)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label_35.setFont(font)
        self.label_35.setObjectName("label_35")
        self.verticalLayout_12.addWidget(self.label_35)
        self.verticalLayout_10 = QtWidgets.QVBoxLayout()
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.horizontalLayout_17 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_17.setObjectName("horizontalLayout_17")
        self.label_7 = QtWidgets.QLabel(parent=self.order_page)
        self.label_7.setObjectName("label_7")
        self.horizontalLayout_17.addWidget(self.label_7)
        spacerItem9 = QtWidgets.QSpacerItem(244, 17, QtWidgets.QSizePolicy.Policy.Expanding,
                                            QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_17.addItem(spacerItem9)
        self.verticalLayout_10.addLayout(self.horizontalLayout_17)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.lineEdit_id_input = QtWidgets.QLineEdit(parent=self.order_page)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_id_input.sizePolicy().hasHeightForWidth())
        self.lineEdit_id_input.setSizePolicy(sizePolicy)
        self.lineEdit_id_input.setStyleSheet("QLineEdit {\n"
                                             "                                                    border: 2px solid white;\n"
                                             "                                                    border-radius: 10px;\n"
                                             "                                                    color: white;\n"
                                             "\n"
                                             "                                                    }\n"
                                             "                                                ")
        self.lineEdit_id_input.setObjectName("lineEdit_id_input")
        self.horizontalLayout_3.addWidget(self.lineEdit_id_input)
        spacerItem10 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding,
                                             QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem10)
        self.verticalLayout_10.addLayout(self.horizontalLayout_3)
        self.verticalLayout_12.addLayout(self.verticalLayout_10)
        self.verticalLayout_11 = QtWidgets.QVBoxLayout()
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.label_6 = QtWidgets.QLabel(parent=self.order_page)
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_10.addWidget(self.label_6)
        spacerItem11 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding,
                                             QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_10.addItem(spacerItem11)
        self.verticalLayout_11.addLayout(self.horizontalLayout_10)
        self.textEdit_com_1 = QtWidgets.QTextEdit(parent=self.order_page)
        self.textEdit_com_1.setStyleSheet("border: 2px solid white;\n"
                                          "                                                    border-radius: 10px;\n"
                                          "                                                    color: white;\n"
                                          "                                                ")
        self.textEdit_com_1.setObjectName("textEdit_com_1")
        self.verticalLayout_11.addWidget(self.textEdit_com_1)
        self.horizontalLayout_16 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_16.setObjectName("horizontalLayout_16")
        self.pushButton_send_order = QtWidgets.QPushButton(parent=self.order_page)
        self.pushButton_send_order.setStyleSheet("\n"
                                                 "                                                                QPushButton{\n"
                                                 "                                                                color: white;\n"
                                                 "                                                                text-align:left;\n"
                                                 "                                                                background-color: rgb(0, 153, 81);\n"
                                                 "                                                                height: 30px;\n"
                                                 "                                                                border:none;\n"
                                                 "                                                                border-radius: 10px;\n"
                                                 "                                                                border-bottom-radius: 10px;\n"
                                                 "                                                                }\n"
                                                 "                                                            ")
        self.pushButton_send_order.setObjectName("pushButton_send_order")
        self.horizontalLayout_16.addWidget(self.pushButton_send_order)
        spacerItem12 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding,
                                             QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_16.addItem(spacerItem12)
        self.verticalLayout_11.addLayout(self.horizontalLayout_16)
        self.verticalLayout_12.addLayout(self.verticalLayout_11)
        self.stackedWidget.addWidget(self.order_page)
        self.tasks_page = QtWidgets.QWidget()
        self.tasks_page.setObjectName("tasks_page")
        self.verticalLayout_13 = QtWidgets.QVBoxLayout(self.tasks_page)
        self.verticalLayout_13.setObjectName("verticalLayout_13")
        self.horizontalLayout_34 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_34.setObjectName("horizontalLayout_34")
        self.verticalLayout_19 = QtWidgets.QVBoxLayout()
        self.verticalLayout_19.setObjectName("verticalLayout_19")
        self.horizontalLayout_32 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_32.setObjectName("horizontalLayout_32")
        self.label_19 = QtWidgets.QLabel(parent=self.tasks_page)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label_19.setFont(font)
        self.label_19.setObjectName("label_19")
        self.horizontalLayout_32.addWidget(self.label_19)
        spacerItem13 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding,
                                             QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_32.addItem(spacerItem13)
        self.pushButton_update_task = QtWidgets.QPushButton(parent=self.tasks_page)
        self.pushButton_update_task.setStyleSheet("\n"
                                                  "                                                                QPushButton{\n"
                                                  "                                                                color: white;\n"
                                                  "                                                                text-align:left;\n"
                                                  "                                                                background-color: rgb(0, 153, 81);\n"
                                                  "                                                                height: 30px;\n"
                                                  "                                                                border:none;\n"
                                                  "                                                                border-radius: 10px;\n"
                                                  "                                                                border-bottom-radius: 10px;\n"
                                                  "                                                                }\n"
                                                  "                                                            ")
        self.pushButton_update_task.setObjectName("pushButton_update_task")
        self.horizontalLayout_32.addWidget(self.pushButton_update_task)
        self.verticalLayout_19.addLayout(self.horizontalLayout_32)
        self.frame_2 = QtWidgets.QFrame(parent=self.tasks_page)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding,
                                           QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_2.sizePolicy().hasHeightForWidth())
        self.frame_2.setSizePolicy(sizePolicy)
        self.frame_2.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_2.setObjectName("frame_2")
        self.verticalLayout_24 = QtWidgets.QVBoxLayout(self.frame_2)
        self.verticalLayout_24.setObjectName("verticalLayout_24")
        self.label_38 = QtWidgets.QLabel(parent=self.frame_2)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label_38.setFont(font)
        self.label_38.setObjectName("label_38")
        self.verticalLayout_24.addWidget(self.label_38)
        self.verticalLayout_19.addWidget(self.frame_2)
        self.frame = QtWidgets.QFrame(parent=self.tasks_page)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding,
                                           QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame.sizePolicy().hasHeightForWidth())
        self.frame.setSizePolicy(sizePolicy)
        self.frame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame.setObjectName("frame")
        self.verticalLayout_23 = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout_23.setObjectName("verticalLayout_23")
        self.horizontalLayout_39 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_39.setObjectName("horizontalLayout_39")
        self.label_39 = QtWidgets.QLabel(parent=self.frame)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label_39.setFont(font)
        self.label_39.setObjectName("label_39")
        self.horizontalLayout_39.addWidget(self.label_39)
        self.label_number_machine = QtWidgets.QLabel(parent=self.frame)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label_number_machine.setFont(font)
        self.label_number_machine.setObjectName("label_number_machine")
        self.horizontalLayout_39.addWidget(self.label_number_machine)
        spacerItem14 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding,
                                             QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_39.addItem(spacerItem14)
        self.verticalLayout_23.addLayout(self.horizontalLayout_39)
        self.verticalLayout_22 = QtWidgets.QVBoxLayout()
        self.verticalLayout_22.setObjectName("verticalLayout_22")
        self.horizontalLayout_40 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_40.setObjectName("horizontalLayout_40")
        self.label_41 = QtWidgets.QLabel(parent=self.frame)
        self.label_41.setObjectName("label_41")
        self.horizontalLayout_40.addWidget(self.label_41)
        spacerItem15 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding,
                                             QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_40.addItem(spacerItem15)
        self.verticalLayout_22.addLayout(self.horizontalLayout_40)
        self.label_coment_disp = QtWidgets.QLabel(parent=self.frame)
        self.label_coment_disp.setObjectName("label_coment_disp")
        self.verticalLayout_22.addWidget(self.label_coment_disp)
        self.verticalLayout_23.addLayout(self.verticalLayout_22)
        self.line = QtWidgets.QFrame(parent=self.frame)
        self.line.setStyleSheet("background-color: rgb(0, 170, 0);")
        self.line.setFrameShape(QtWidgets.QFrame.Shape.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.line.setObjectName("line")
        self.verticalLayout_23.addWidget(self.line)
        self.verticalLayout_19.addWidget(self.frame)
        self.horizontalLayout_34.addLayout(self.verticalLayout_19)
        self.verticalLayout_18 = QtWidgets.QVBoxLayout()
        self.verticalLayout_18.setObjectName("verticalLayout_18")
        self.horizontalLayout_26 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_26.setObjectName("horizontalLayout_26")
        self.verticalLayout_18.addLayout(self.horizontalLayout_26)
        self.horizontalLayout_27 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_27.setObjectName("horizontalLayout_27")
        self.verticalLayout_18.addLayout(self.horizontalLayout_27)
        self.horizontalLayout_34.addLayout(self.verticalLayout_18)
        self.verticalLayout_13.addLayout(self.horizontalLayout_34)
        self.horizontalLayout_31 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_31.setObjectName("horizontalLayout_31")
        self.verticalLayout_16 = QtWidgets.QVBoxLayout()
        self.verticalLayout_16.setObjectName("verticalLayout_16")
        self.horizontalLayout_28 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_28.setObjectName("horizontalLayout_28")
        self.label_22 = QtWidgets.QLabel(parent=self.tasks_page)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label_22.setFont(font)
        self.label_22.setObjectName("label_22")
        self.horizontalLayout_28.addWidget(self.label_22)
        spacerItem16 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding,
                                             QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_28.addItem(spacerItem16)
        self.verticalLayout_16.addLayout(self.horizontalLayout_28)
        self.textEdit_com__unsucses = QtWidgets.QTextEdit(parent=self.tasks_page)
        self.textEdit_com__unsucses.setStyleSheet("border: 2px solid white;\n"
                                                  "                                                    border-radius: 10px;\n"
                                                  "                                                    color: white;\n"
                                                  "                                                ")
        self.textEdit_com__unsucses.setObjectName("textEdit_com__unsucses")
        self.verticalLayout_16.addWidget(self.textEdit_com__unsucses)
        self.horizontalLayout_29 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_29.setObjectName("horizontalLayout_29")
        self.pushButton_send_order_unsucses = QtWidgets.QPushButton(parent=self.tasks_page)
        self.pushButton_send_order_unsucses.setStyleSheet("\n"
                                                          "                                                                QPushButton{\n"
                                                          "                                                                color: white;\n"
                                                          "                                                                text-align:left;\n"
                                                          "                                                                background-color: rgb(0, 153, 81);\n"
                                                          "                                                                height: 30px;\n"
                                                          "                                                                border:none;\n"
                                                          "                                                                border-radius: 10px;\n"
                                                          "                                                                border-bottom-radius: 10px;\n"
                                                          "                                                                }\n"
                                                          "                                                            ")
        self.pushButton_send_order_unsucses.setObjectName("pushButton_send_order_unsucses")
        self.horizontalLayout_29.addWidget(self.pushButton_send_order_unsucses)
        spacerItem17 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding,
                                             QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_29.addItem(spacerItem17)
        self.verticalLayout_16.addLayout(self.horizontalLayout_29)
        self.horizontalLayout_31.addLayout(self.verticalLayout_16)
        self.line_2 = QtWidgets.QFrame(parent=self.tasks_page)
        self.line_2.setStyleSheet("background-color: rgb(0, 170, 0);")
        self.line_2.setFrameShape(QtWidgets.QFrame.Shape.VLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.line_2.setObjectName("line_2")
        self.horizontalLayout_31.addWidget(self.line_2)
        self.verticalLayout_17 = QtWidgets.QVBoxLayout()
        self.verticalLayout_17.setObjectName("verticalLayout_17")
        self.label_2 = QtWidgets.QLabel(parent=self.tasks_page)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding,
                                           QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_2.sizePolicy().hasHeightForWidth())
        self.label_2.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_17.addWidget(self.label_2)
        self.horizontalLayout_30 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_30.setObjectName("horizontalLayout_30")
        self.pushButton_send_order_sucses = QtWidgets.QPushButton(parent=self.tasks_page)
        self.pushButton_send_order_sucses.setStyleSheet("\n"
                                                        "                                                                QPushButton{\n"
                                                        "                                                                color: white;\n"
                                                        "                                                                text-align:left;\n"
                                                        "                                                                background-color: rgb(0, 153, 81);\n"
                                                        "                                                                height: 30px;\n"
                                                        "                                                                border:none;\n"
                                                        "                                                                border-radius: 10px;\n"
                                                        "                                                                border-bottom-radius: 10px;\n"
                                                        "                                                                }\n"
                                                        "                                                            ")
        self.pushButton_send_order_sucses.setObjectName("pushButton_send_order_sucses")
        self.horizontalLayout_30.addWidget(self.pushButton_send_order_sucses)
        spacerItem18 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding,
                                             QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_30.addItem(spacerItem18)
        self.verticalLayout_17.addLayout(self.horizontalLayout_30)
        spacerItem19 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum,
                                             QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout_17.addItem(spacerItem19)
        self.horizontalLayout_31.addLayout(self.verticalLayout_17)
        self.verticalLayout_13.addLayout(self.horizontalLayout_31)
        self.stackedWidget.addWidget(self.tasks_page)
        self.verticalLayout_6.addWidget(self.stackedWidget)
        self.gridLayout.addWidget(self.widget_3, 1, 3, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.stackedWidget.setCurrentIndex(3)
        self.pushButton.toggled['bool'].connect(self.widget_4.setHidden)  # type: ignore
        self.pushButton.toggled['bool'].connect(self.widget_5.setVisible)  # type: ignore
        self.pushButton_education1us.toggled['bool'].connect(self.pushButton_education2_us.setChecked)  # type: ignore
        self.pushButton_acc1_us.toggled['bool'].connect(self.pushButton_acc2_us.setChecked)  # type: ignore
        self.pushButton_acc2_us.toggled['bool'].connect(self.pushButton_acc1_us.setChecked)  # type: ignore
        self.pushButton_education2_us.toggled['bool'].connect(self.pushButton_education1us.setChecked)  # type: ignore
        self.pushButton_23.toggled['bool'].connect(MainWindow.close)  # type: ignore
        self.pushButton_logout1.toggled['bool'].connect(self.pushButton_12.setChecked)  # type: ignore
        self.pushButton_12.toggled['bool'].connect(self.pushButton_logout1.setChecked)  # type: ignore
        self.pushButton_order2_2.toggled['bool'].connect(self.pushButton_orde1_2.setChecked)  # type: ignore
        self.pushButton_orde1_2.toggled['bool'].connect(self.pushButton_order2_2.setChecked)  # type: ignore
        self.pushButton_tasks2.toggled['bool'].connect(self.pushButton_task1.setChecked)  # type: ignore
        self.pushButton_task1.toggled['bool'].connect(self.pushButton_tasks2.setChecked)  # type: ignore
        self.pushButton_22.toggled['bool'].connect(MainWindow.showMaximized)  # type: ignore
        self.pushButton_22.toggled['bool'].connect(self.pushButton_22.hide)  # type: ignore
        self.pushButton_24.toggled['bool'].connect(MainWindow.showNormal)  # type: ignore
        self.pushButton_24.toggled['bool'].connect(self.pushButton_24.hide)  # type: ignore
        self.pushButton_24.toggled['bool'].connect(self.pushButton_22.show)  # type: ignore
        self.pushButton_22.toggled['bool'].connect(self.pushButton_24.show)  # type: ignore
        self.pushButton_13.toggled['bool'].connect(MainWindow.setHidden)  # type: ignore
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_nick.setText(_translate("MainWindow", "TextLabel"))
        self.label.setText(_translate("MainWindow", "Хорошего рабочего дня!"))
        self.label_nick2.setText(_translate("MainWindow", "TextLabel"))
        self.pushButton_acc2_us.setText(_translate("MainWindow", "Акаунт"))
        self.pushButton_education2_us.setText(_translate("MainWindow", "Обучение"))
        self.pushButton_order2_2.setText(_translate("MainWindow", "Заявки"))
        self.pushButton_tasks2.setText(_translate("MainWindow", "Задачи"))
        self.pushButton_12.setText(_translate("MainWindow", "Выход"))
        self.pushButton_link1.setText(_translate("MainWindow", "Повысить квалификацию"))
        self.pushButton_link2.setText(_translate("MainWindow", "Повысить квалификацию"))
        self.pushButton_link3.setText(_translate("MainWindow", "Повысить квалификацию"))
        self.label_31.setText(_translate("MainWindow",
                                         "На курсе вы узнаете про устройство и эксплуатацию токарныx станков, правилам заточки и термообработки, а также вспомните основные свойства обрабатываемых материалов. После вы сможете применять эти знания непосредственно на практике.                                                "))
        self.label_32.setText(_translate("MainWindow",
                                         "Курс обучает методам консервации и хранения техники, предотвращению её повреждения и безопасной транспортировке. Слушатели освоят технологии, материалы и принципы сохранения техники"))
        self.label_33.setText(_translate("MainWindow",
                                         "Специалисты на производстве, стройплощадках, станциях технического обслуживания и других объектах сваривают и режут металлические или полимерные изделия. Наладчики оборудования и операторы установок контролируют режимы работы и исправность спецтехники."))
        self.label_30.setText(_translate("MainWindow", "Повышение квалификация"))
        self.label_18.setText(_translate("MainWindow", "Никнейм"))
        self.label_nik.setText(_translate("MainWindow", "TextLabel"))
        self.label_11.setText(_translate("MainWindow", "Отчество"))
        self.label_midlename.setText(_translate("MainWindow", "TextLabel"))
        self.label_9.setText(_translate("MainWindow", "Фамилия"))
        self.label_secondnaame.setText(_translate("MainWindow", "TextLabel"))
        self.label_10.setText(_translate("MainWindow", "Имя"))
        self.label_name.setText(_translate("MainWindow", "TextLabel"))
        self.label_16.setText(_translate("MainWindow", "Должность"))
        self.label_post.setText(_translate("MainWindow", "TextLabel"))
        self.label_13.setText(_translate("MainWindow", "Возраст"))
        self.label_age.setText(_translate("MainWindow", "TextLabel"))
        self.label_14.setText(_translate("MainWindow", "Разряд"))
        self.label_level.setText(_translate("MainWindow", "TextLabel"))
        self.label_15.setText(_translate("MainWindow", "Стаж"))
        self.label_exp.setText(_translate("MainWindow", "TextLabel"))
        self.label_34.setText(_translate("MainWindow", "Расскажи о себе"))
        self.label_35.setText(_translate("MainWindow", "Сломалось? оборудование не беда, отправь заявку!"))
        self.label_7.setText(_translate("MainWindow", "Введите номер станка"))
        self.label_6.setText(_translate("MainWindow", "Введите личный коментарий(по желанию)"))
        self.pushButton_send_order.setText(_translate("MainWindow", "Отправить заявку"))
        self.label_19.setText(_translate("MainWindow", "Твоя задача"))
        self.pushButton_update_task.setText(_translate("MainWindow", "Отправить заявку"))
        self.label_38.setText(_translate("MainWindow", "Пока у тебя не задач отдыхый)"))
        self.label_39.setText(_translate("MainWindow", "Починка станка №:"))
        self.label_number_machine.setText(_translate("MainWindow", "TextLabel"))
        self.label_41.setText(_translate("MainWindow", "Комментарий к работе"))
        self.label_coment_disp.setText(_translate("MainWindow", "TextLabel"))
        self.label_22.setText(_translate("MainWindow", "Не получилось? Напиши комментарий."))
        self.pushButton_send_order_unsucses.setText(_translate("MainWindow", "Отправить заявку"))
        self.label_2.setText(_translate("MainWindow", "Сделал работу? Молодец! отправь отчёт."))
        self.pushButton_send_order_sucses.setText(_translate("MainWindow", "Отправить заявку"))
